const modal=document.getElementById('projectModal');
const title=document.getElementById('modalTitle');
const gallery=document.getElementById('modalGallery');
document.querySelectorAll('.view-project').forEach(btn=>{btn.addEventListener('click',()=>{title.textContent=btn.dataset.title;const imgs=JSON.parse(btn.dataset.images);gallery.innerHTML=imgs.map(x=>`<img src="assets/${x}" alt="${btn.dataset.title} project image" loading="lazy">`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';});});
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';}
document.querySelector('.modal-close').addEventListener('click',closeModal);document.querySelector('.modal-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')});},{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));

(function(){var root=document.querySelector('.bbs-slideshow');if(!root)return;var track=root.querySelector('.bbs-slides');if(!track)return;var slides=track.children,n=slides.length;if(n<2)return;var cur=root.querySelector('.bbs-current'),total=root.querySelector('.bbs-total'),prev=root.querySelector('.bbs-prev'),next=root.querySelector('.bbs-next'),i=0;if(total)total.textContent=n;function go(idx){i=(idx+n)%n;track.style.transform='translateX('+(-i*100)+'%)';if(cur)cur.textContent=i+1;}if(prev)prev.addEventListener('click',function(){go(i-1)});if(next)next.addEventListener('click',function(){go(i+1)});var playing=true,timer=null;function play(){if(playing)timer=setInterval(function(){go(i+1)},4500)}function stop(){if(timer)clearInterval(timer)}play();root.addEventListener('mouseenter',stop);root.addEventListener('mouseleave',play);var io=new IntersectionObserver(function(ents){ents.forEach(function(e){if(e.isIntersecting){playing=true;stop();play()}else{playing=false;stop()}})},{threshold:.2});io.observe(root);})();

(function(){var el=document.getElementById('goatcounter-counter');if(!el)return;var tries=0;function counterUrl(){var s=document.querySelector('script[data-goatcounter]');if(!s||!s.dataset.goatcounter)return null;var base=s.dataset.goatcounter.replace(/\/count\/?$/,'');return base+'/counter/TOTAL.json?no_branding=1';}function render(){if(!window.goatcounter){if(tries<40){tries++;setTimeout(render,250);return}el.textContent='\u2014';return}var url=counterUrl();if(!url){el.textContent='\u2014';return}fetch(url).then(function(res){if(!res.ok)throw new Error('HTTP '+res.status);return res.json()}).then(function(data){el.textContent=data&&typeof data.count==='string'?data.count:'\u2014'}).catch(function(){el.textContent='\u2014'})}render();})();

/* PROJECT CAROUSEL — smooth 1 second auto-advance, pauses on hover/touch */
(function(){
  var grid=document.querySelector('.project-grid');if(!grid)return;
  var cards=grid.querySelectorAll('.project-card');if(cards.length<2)return;
  var section=grid.closest('#projects')||grid.parentElement;section.classList.add('project-carousel-section');grid.classList.add('project-carousel');
  var controls=document.createElement('div');controls.className='project-carousel-controls';controls.innerHTML='<button type="button" class="project-carousel-btn project-carousel-prev" aria-label="Previous projects">←</button><span class="project-carousel-label">PROJECTS <b>01</b> / '+String(cards.length).padStart(2,'0')+'</span><button type="button" class="project-carousel-btn project-carousel-next" aria-label="Next projects">→</button>';grid.parentNode.insertBefore(controls,grid);
  var prev=controls.querySelector('.project-carousel-prev'),next=controls.querySelector('.project-carousel-next'),current=controls.querySelector('.project-carousel-label b');
  var style=document.createElement('style');style.textContent=`#projects.project-carousel-section{position:relative}#projects .project-carousel-controls{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin:-28px 0 28px}#projects .project-carousel-label{font:700 10px/1 "Space Grotesk",sans-serif;letter-spacing:.14em;color:#777;margin-right:4px}#projects .project-carousel-label b{color:#111}#projects .project-carousel{display:flex!important;grid-template-columns:none!important;gap:22px!important;overflow-x:auto;overflow-y:visible;scroll-snap-type:x mandatory;scroll-behavior:smooth;padding:4px 4px 24px;margin:0 -4px;-ms-overflow-style:none;scrollbar-width:none;cursor:grab}#projects .project-carousel::-webkit-scrollbar{display:none}#projects .project-carousel:active{cursor:grabbing}#projects .project-carousel .project-card{flex:0 0 calc((100% - 44px)/3);min-width:0;scroll-snap-align:start}#projects .project-carousel-btn{width:42px;height:42px;border:1px solid #c8c5bc;border-radius:50%;background:#ebe9e2;color:#111;font:700 20px/1 "Space Grotesk",sans-serif;cursor:pointer;display:grid;place-items:center;transition:transform .2s ease,background .2s ease,border-color .2s ease}#projects .project-carousel-btn:hover{transform:translateY(-2px);background:#c9ff38;border-color:#111}@media(max-width:1050px){#projects .project-carousel .project-card{flex-basis:calc((100% - 22px)/2)}}@media(max-width:700px){#projects .project-carousel-controls{justify-content:space-between;margin:-12px 0 20px}#projects .project-carousel .project-card{flex-basis:88%}#projects .project-carousel{gap:14px;padding-bottom:18px}#projects .project-carousel-btn{width:38px;height:38px;font-size:18px}#projects .project-carousel-label{margin:0 auto}}`;document.head.appendChild(style);
  function cardStep(){var first=cards[0];if(!first)return grid.clientWidth;var gap=parseFloat(getComputedStyle(grid).gap)||22;return first.getBoundingClientRect().width+gap}
  function go(direction){grid.scrollBy({left:direction*cardStep(),behavior:'smooth'})}
  prev.addEventListener('click',function(){go(-1)});next.addEventListener('click',function(){go(1)});
  grid.addEventListener('scroll',function(){var index=Math.round(grid.scrollLeft/cardStep());index=Math.max(0,Math.min(cards.length-1,index));current.textContent=String(index+1).padStart(2,'0')},{passive:true});
  grid.addEventListener('wheel',function(e){if(Math.abs(e.deltaY)>Math.abs(e.deltaX)){e.preventDefault();grid.scrollLeft+=e.deltaY}},{passive:false});
  var autoTimer=null,autoDelay=1000,paused=false;
  function start(){if(autoTimer||paused)return;autoTimer=setInterval(function(){if(grid.scrollLeft>=grid.scrollWidth-grid.clientWidth-3){grid.scrollTo({left:0,behavior:'smooth'});}else{go(1);}},autoDelay)}
  function stop(){if(autoTimer){clearInterval(autoTimer);autoTimer=null}}
  function pause(){paused=true;stop()}
  function resume(){paused=false;start()}
  grid.addEventListener('mouseenter',pause);grid.addEventListener('mouseleave',resume);grid.addEventListener('touchstart',pause,{passive:true});grid.addEventListener('touchend',resume,{passive:true});grid.addEventListener('touchcancel',resume,{passive:true});grid.addEventListener('pointerdown',pause);grid.addEventListener('pointerup',function(){if(!grid.matches(':hover'))resume()});grid.addEventListener('pointercancel',resume);window.addEventListener('resize',function(){stop();if(!paused)start()});start();
})();

/* SYSTEM / LIGHT / DARK THEME TOGGLE */
(function(){
  var style=document.createElement('style');style.textContent=`:root{color-scheme:light}html[data-theme="dark"]{color-scheme:dark}html[data-theme="dark"] body{--bg:#0c0d0d;--ink:#f4f4ef;--muted:#a5a59d;--line:#30312e;background:var(--bg);color:var(--ink)}html[data-theme="dark"] .site-header{background:rgba(12,13,13,.92);border-color:#30312e}html[data-theme="dark"] .site-header nav{color:#bdbdb5}html[data-theme="dark"] .site-header nav a:hover{color:#fff}html[data-theme="dark"] .nav-cta{border-color:#aaa;color:#fff}html[data-theme="dark"] .brand span{background:#f4f4ef;color:#111}html[data-theme="dark"] .hero h1 em{color:#aaa}html[data-theme="dark"] .hero-text,html[data-theme="dark"] .large{color:#bdbdb5}html[data-theme="dark"] .pill-row span{border-color:#30312e}html[data-theme="dark"] .project-card{background:#171918;border-color:#30312e}html[data-theme="dark"] .project-media{background:#222421}html[data-theme="dark"] .view-project{color:#fff;border-color:#aaa}html[data-theme="dark"] .process-section,html[data-theme="dark"] .process-step{background:#151716}html[data-theme="dark"] .process-grid{background:#30312e}html[data-theme="dark"] .contact-card{background:#f4f4ef;color:#111}html[data-theme="dark"] .contact-card p{color:#555}html[data-theme="dark"] .contact-details a,html[data-theme="dark"] .contact-details div{border-color:#d0d0ca}html[data-theme="dark"] footer{border-color:#30312e}html[data-theme="dark"] .modal-box{background:#111312;color:#f4f4ef}.theme-switcher{display:inline-flex;align-items:center;gap:2px;padding:3px;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.45);backdrop-filter:blur(10px);margin-left:10px}.theme-switcher button{width:30px;height:30px;border:0;background:transparent;color:var(--muted);border-radius:50%;cursor:pointer;font:700 12px/1 "DM Sans",sans-serif;display:grid;place-items:center;transition:.2s ease}.theme-switcher button:hover{color:var(--ink)}.theme-switcher button.active{background:var(--ink);color:var(--bg)}html[data-theme="dark"] .theme-switcher{background:rgba(255,255,255,.05)}html[data-theme="dark"] .project-carousel-btn{background:#191b1a;color:#fff;border-color:#444}html[data-theme="dark"] .project-carousel-label{color:#999}html[data-theme="dark"] .project-carousel-label b{color:#fff}@media(max-width:850px){.theme-switcher{margin-left:auto;margin-right:8px}.theme-switcher button{width:28px;height:28px}}`;document.head.appendChild(style);
  var header=document.querySelector('.site-header');if(!header)return;var switcher=document.createElement('div');switcher.className='theme-switcher';switcher.setAttribute('role','group');switcher.setAttribute('aria-label','Theme');switcher.innerHTML='<button type="button" data-theme-choice="system" title="System default" aria-label="System default">◐</button><button type="button" data-theme-choice="light" title="Light theme" aria-label="Light theme">☀</button><button type="button" data-theme-choice="dark" title="Dark theme" aria-label="Dark theme">☾</button>';var cta=header.querySelector('.nav-cta');if(cta)header.insertBefore(switcher,cta);else header.appendChild(switcher);var buttons=switcher.querySelectorAll('button');
  function systemDark(){return window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches}
  function applyTheme(choice){if(choice==='system'){document.documentElement.removeAttribute('data-theme');document.documentElement.style.colorScheme=systemDark()?'dark':'light'}else{document.documentElement.setAttribute('data-theme',choice);document.documentElement.style.colorScheme=choice}localStorage.setItem('portfolio-theme',choice);buttons.forEach(function(b){b.classList.toggle('active',b.dataset.themeChoice===choice)})}
  var saved=localStorage.getItem('portfolio-theme')||'system';applyTheme(saved);
  if(window.matchMedia){var media=window.matchMedia('(prefers-color-scheme: dark)');var onSystemChange=function(){if((localStorage.getItem('portfolio-theme')||'system')==='system')applyTheme('system')};if(media.addEventListener)media.addEventListener('change',onSystemChange);else if(media.addListener)media.addListener(onSystemChange)}
  buttons.forEach(function(b){b.addEventListener('click',function(){applyTheme(b.dataset.themeChoice)})});
})();

/* BRAND VISUAL SYSTEM v1.0.0 — playful handwritten typography + neon BIM UI */
(function(){
  var font=document.createElement('link');font.rel='stylesheet';font.href='https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Patrick+Hand&family=Space+Grotesk:wght@500;600;700&display=swap';document.head.appendChild(font);
  var style=document.createElement('style');
  style.textContent=`
    :root{--brand-pink:#ff4fa3;--brand-purple:#7b5cff;--brand-blue:#32a8ff;--brand-cyan:#5be7ff;--brand-green:#55e68a;--brand-yellow:#ffd45a;--brand-card:rgba(255,255,255,.72);--brand-shadow:0 24px 70px rgba(91,75,180,.13)}
    body{font-family:"DM Sans",sans-serif;background:radial-gradient(circle at 12% 8%,rgba(123,92,255,.10),transparent 25%),radial-gradient(circle at 88% 14%,rgba(255,79,163,.08),transparent 24%),var(--bg);}
    .site-header{height:82px;border-bottom:1px solid rgba(123,92,255,.16);background:rgba(243,241,235,.72);box-shadow:0 10px 40px rgba(60,50,120,.07);}
    .brand,.hero h1,h2,h3,.about-lead,.stats strong,.hero-badge,.section-number{font-family:"Patrick Hand",cursive;letter-spacing:0}
    .brand{font-size:25px;line-height:1;color:#26222f;display:flex;align-items:center;gap:8px}.brand span{width:38px;height:38px;border-radius:13px;background:linear-gradient(135deg,var(--brand-pink),var(--brand-purple));box-shadow:0 8px 25px rgba(123,92,255,.25);font:700 13px "DM Sans";}
    .site-header nav{font-family:"Patrick Hand",cursive;font-size:18px;gap:25px}.site-header nav a{position:relative}.site-header nav a:after{content:"";position:absolute;left:50%;bottom:-10px;width:0;height:3px;border-radius:99px;background:linear-gradient(90deg,var(--brand-pink),var(--brand-purple));transform:translateX(-50%);transition:.25s}.site-header nav a:hover:after{width:75%}
    .nav-cta{font-family:"Patrick Hand",cursive;font-size:17px;padding:9px 18px;border:1px solid var(--brand-purple);background:linear-gradient(90deg,rgba(255,79,163,.08),rgba(123,92,255,.08));}
    .hero{padding-top:5vw;padding-bottom:6vw}.hero-grid{max-width:1380px;gap:5vw}.hero-copy{max-width:650px}.hero-copy:before{content:"✦ BIM  •  REVIT  •  3D  •  BOQ  •  BBS ✦";font:700 12px "Patrick Hand";letter-spacing:.08em;color:var(--brand-purple);margin-bottom:20px}
    .availability{background:rgba(123,92,255,.10);color:var(--brand-purple);border:1px solid rgba(123,92,255,.2);font-family:"Patrick Hand",cursive;font-size:15px}
    .hero h1{font-size:clamp(58px,7vw,104px);line-height:.92;letter-spacing:.01em;color:#292434;text-shadow:0 4px 24px rgba(123,92,255,.08)}
    .hero h1 em{font-style:normal;background:linear-gradient(90deg,var(--brand-pink),var(--brand-purple),var(--brand-blue));-webkit-background-clip:text;background-clip:text;color:transparent;position:relative}
    .hero h1 em:after{content:"♡";font-family:"Patrick Hand";font-size:.42em;color:var(--brand-pink);position:absolute;right:-.45em;top:-.35em;transform:rotate(12deg)}
    .hero-text{font-family:"DM Sans";font-size:16px;text-transform:none;letter-spacing:.02em;color:#575361;max-width:650px}
    .hero-actions{margin:28px 0 40px}.btn{font-family:"Patrick Hand",cursive;font-size:18px;padding:12px 22px}.btn.primary{border:0;background:linear-gradient(100deg,var(--brand-pink),var(--brand-purple));box-shadow:0 12px 32px rgba(123,92,255,.25)}.btn.ghost{border:1px solid rgba(123,92,255,.45);background:rgba(255,255,255,.45)}
    .stats{gap:28px}.stats div{padding-right:24px;border-right:1px solid rgba(123,92,255,.18)}.stats div:last-child{border-right:0}.stats strong{font-size:30px;background:linear-gradient(90deg,var(--brand-pink),var(--brand-purple));-webkit-background-clip:text;background-clip:text;color:transparent}.stats span{font-size:10px}
    .hero-frame{border-radius:34px;background:linear-gradient(135deg,#17112a,#091b36);box-shadow:0 35px 90px rgba(43,22,89,.25);border:1px solid rgba(123,92,255,.35)}.hero-frame:before{content:"";position:absolute;inset:-2px;border-radius:36px;background:linear-gradient(135deg,var(--brand-pink),transparent 35%,var(--brand-blue));z-index:-1;filter:blur(10px);opacity:.45}.hero-frame:after{content:"BIM";font-family:"Patrick Hand";font-size:105px;color:rgba(255,255,255,.08);}
    .hero-badge{background:linear-gradient(135deg,var(--brand-purple),var(--brand-pink));color:#fff;border-radius:20px;box-shadow:0 14px 40px rgba(123,92,255,.35);font-size:28px}.hero-badge small{font-family:"DM Sans"}
    .section{padding-top:105px;padding-bottom:105px}.section-head{margin-bottom:45px}.section-number{font-size:25px;color:var(--brand-pink)}.section h2{font-size:clamp(44px,5.5vw,76px);color:#292434}.kicker{font-family:"Patrick Hand",cursive;font-size:16px;letter-spacing:.08em;color:var(--brand-purple)}
    .about-lead{font-size:clamp(38px,4vw,62px);background:linear-gradient(90deg,var(--brand-pink),var(--brand-purple));-webkit-background-clip:text;background-clip:text;color:transparent}.large{font-size:19px}
    .pill-row span{font-family:"Patrick Hand",cursive;font-size:16px;border-color:rgba(123,92,255,.2);background:rgba(255,255,255,.5)}
    .section.dark{background:radial-gradient(circle at 15% 10%,rgba(123,92,255,.22),transparent 28%),radial-gradient(circle at 85% 80%,rgba(255,79,163,.14),transparent 25%),#0c0d18;border-top:1px solid rgba(123,92,255,.22);border-bottom:1px solid rgba(123,92,255,.22)}.section.dark .section h2{color:#fff}.section.dark .kicker{color:#8ecbff}.section.dark .section-number{color:var(--brand-pink)}
    .skills-grid{background:rgba(123,92,255,.25);gap:1px}.skill-card{background:rgba(15,16,29,.88);border-color:rgba(123,92,255,.15);border-radius:0;transition:.3s}.skill-card:hover{background:linear-gradient(145deg,rgba(123,92,255,.18),rgba(255,79,163,.08));transform:translateY(-5px)}.skill-no{font-family:"Patrick Hand";font-size:18px;color:var(--brand-pink)}.skill-card h3{font-size:31px;color:#fff}.skill-card p{color:#aeb0c0}.achievement{border-color:rgba(123,92,255,.25)}.achievement span{color:var(--brand-cyan);font-family:"Patrick Hand";font-size:16px}
    #projects{position:relative}.project-carousel-section:before{content:"";position:absolute;inset:35px 0 auto;height:260px;background:radial-gradient(circle at 25% 50%,rgba(255,79,163,.09),transparent 32%),radial-gradient(circle at 75% 50%,rgba(123,92,255,.09),transparent 32%);pointer-events:none}.project-card{border:1px solid rgba(123,92,255,.18);background:var(--brand-card);border-radius:26px;box-shadow:var(--brand-shadow);backdrop-filter:blur(12px);overflow:hidden}.project-card:hover{transform:translateY(-9px) rotate(-.3deg);box-shadow:0 30px 70px rgba(123,92,255,.19)}.project-media{background:linear-gradient(135deg,#e8e5ff,#ffe8f2);border-radius:0}.project-media:after{background:linear-gradient(90deg,var(--brand-pink),var(--brand-purple));font-family:"Patrick Hand";font-size:12px}.project-body h3{font-size:35px;background:linear-gradient(90deg,var(--brand-purple),var(--brand-pink));-webkit-background-clip:text;background-clip:text;color:transparent}.eyebrow{font-family:"Patrick Hand";font-size:15px;letter-spacing:.03em;color:#6d5f83}.view-project{font-family:"Patrick Hand";font-size:17px;color:#352d46;border-bottom:2px solid var(--brand-pink)}
    .project-carousel-controls{position:relative;z-index:2}.project-carousel-label{font-family:"Patrick Hand",cursive!important;font-size:16px!important;color:#6d5f83!important}.project-carousel-label b{color:var(--brand-pink)!important;font-size:21px}.project-carousel-btn{border:1px solid rgba(123,92,255,.3)!important;background:linear-gradient(135deg,#fff,#f4efff)!important;color:var(--brand-purple)!important;box-shadow:0 8px 24px rgba(123,92,255,.12)}.project-carousel-btn:hover{background:linear-gradient(135deg,var(--brand-pink),var(--brand-purple))!important;color:#fff!important}
    .bbs-slideshow{border:1px solid rgba(123,92,255,.28);box-shadow:0 25px 70px rgba(65,42,120,.18)}.bbs-nav{background:linear-gradient(135deg,var(--brand-pink),var(--brand-purple));font-family:"Patrick Hand"}.bbs-slide-count{font-family:"Patrick Hand";font-size:16px;background:rgba(13,14,25,.78)}
    .process-section{background:linear-gradient(135deg,#f1edff,#fff1f7)}.process-grid{background:rgba(123,92,255,.2)}.process-step{background:rgba(255,255,255,.72);transition:.3s}.process-step:hover{background:#fff;transform:translateY(-4px)}.process-step h3{font-size:33px;color:#463b66}.process-step span{font-family:"Patrick Hand";font-size:17px;color:var(--brand-purple)}
    .contact-card{background:radial-gradient(circle at 80% 20%,rgba(123,92,255,.35),transparent 28%),linear-gradient(135deg,#111120,#19102b);border:1px solid rgba(123,92,255,.3);box-shadow:0 30px 80px rgba(40,24,90,.25);border-radius:32px}.contact-card h2{font-family:"Patrick Hand";font-size:clamp(50px,6vw,82px);color:#fff}.contact-card p{color:#b9b8c6}.contact-details a,.contact-details div{border-color:rgba(255,255,255,.15)}footer{border-color:rgba(123,92,255,.15)}
    .modal-box{border:1px solid rgba(123,92,255,.25);box-shadow:0 35px 100px rgba(0,0,0,.35)}.modal-box h2{font-family:"Patrick Hand";background:linear-gradient(90deg,var(--brand-pink),var(--brand-purple));-webkit-background-clip:text;background-clip:text;color:transparent}
    .theme-switcher{border-color:rgba(123,92,255,.28);background:rgba(255,255,255,.6);box-shadow:0 8px 25px rgba(123,92,255,.08)}.theme-switcher button{font-family:"Patrick Hand";font-size:16px}
    @media(max-width:850px){.brand{font-size:21px}.site-header{height:70px}.hero{padding-top:35px}.hero h1{font-size:clamp(52px,15vw,76px)}.hero-frame{border-radius:25px}.stats{gap:14px}.stats div{padding-right:13px}.stats strong{font-size:26px}.section h2{font-size:clamp(42px,11vw,64px)}}

    /* Dark theme keeps the same playful brand system without losing contrast. */
    html[data-theme="dark"] body{background:radial-gradient(circle at 10% 5%,rgba(123,92,255,.18),transparent 25%),radial-gradient(circle at 90% 15%,rgba(255,79,163,.14),transparent 25%),#080914;color:#f5f2ff}
    html[data-theme="dark"] .site-header{background:rgba(8,9,20,.72);border-color:rgba(123,92,255,.25)}html[data-theme="dark"] .brand{color:#fff}html[data-theme="dark"] .site-header nav{color:#d6d0e2}html[data-theme="dark"] .nav-cta{color:#fff;border-color:rgba(255,79,163,.6);background:rgba(123,92,255,.12)}
    html[data-theme="dark"] .hero h1,html[data-theme="dark"] .section h2{color:#fff}html[data-theme="dark"] .hero-text,html[data-theme="dark"] .large{color:#c2becd}html[data-theme="dark"] .pill-row span{background:rgba(255,255,255,.04);border-color:rgba(123,92,255,.3);color:#ddd8e7}
    html[data-theme="dark"] .project-card{background:linear-gradient(145deg,rgba(24,20,42,.92),rgba(13,18,35,.92));border-color:rgba(123,92,255,.32)}html[data-theme="dark"] .project-media{background:#111426}html[data-theme="dark"] .eyebrow{color:#bdb5cf}html[data-theme="dark"] .view-project{color:#fff}html[data-theme="dark"] .project-carousel-btn{background:linear-gradient(135deg,#19152d,#111b35)!important;color:#cbbdff!important;border-color:rgba(123,92,255,.4)!important}
    html[data-theme="dark"] .process-section{background:radial-gradient(circle at 20% 10%,rgba(123,92,255,.15),transparent 30%),#10101c}html[data-theme="dark"] .process-step{background:rgba(18,18,31,.88);color:#fff}html[data-theme="dark"] .process-step h3{color:#fff}html[data-theme="dark"] .process-step p{color:#aaa6b7}html[data-theme="dark"] .process-grid{background:rgba(123,92,255,.28)}
    html[data-theme="dark"] .modal-box{background:#0e0f1a;color:#fff}
    @media(prefers-reduced-motion:reduce){.project-card,.skill-card,.process-step,.btn{transition:none!important}.project-carousel{scroll-behavior:auto!important}}
  `;
  document.head.appendChild(style);
  var meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content='#0b0c18';
})();
